### ISSUE TITLE
你好，能否介绍一下训练过程，想复现下

### ISSUE THREAD

**Issue by PeterPanUnderhill** [renmada/sentence_bert_chinese#3]
我的理解都是用sentence-transformer的训练代码，都在examples里面。

**数据集**
1. sts任务：ChineseSTS
2. NLI任务：CLUE-CMNLI 和 ChineseTextualInference都用了吗？
除了上述的数据集，还有用到其他吗？

**训练方式**
如果缺失利用sentence-transformer的训练代码，我的疑问是不同的任务是串行训练，还是用multitask的任务同时训练呢？

谢谢！

**Comment by renmada** [comment]
**数据集**
不仅仅是你列出来的这些，几乎把中文的sts、nli数据集都用上了
**训练方式**
是串行的，先nli然后sts
