### ISSUE TITLE
如何用transformers库调用模型

### ISSUE THREAD

**Issue by TheHonestBob** [renmada/sentence_bert_chinese#4]
首先感谢你的开源项目，有一个问题就是我可以使用transforms库调用模型吗？我看案例是sentence-transforms

**Comment by renmada** [comment]
可以，根据sentence-transforms的代码去改pooling
新手的话建议使用sentence-transforms

**Comment by TheHonestBob** [comment]
> 可以，根据sentence-transforms的代码去改pooling 新手的话建议使用sentence-transforms

好的，谢谢
